package rules.Preupdate.ClaimPreupdate_dir

@gw.rules.RuleName("CPU45000 - Trigger SMS Event on Adjuster Assignment")
internal class CPU45000TriggerSMSEventonAdjusterAssignment {
  static function doCondition(claim : entity.Claim) : boolean {
/*start00rule*/
return true
/*end00rule*/
}

  static function doAction(claim : entity.Claim, actions : gw.rules.Action) {
/*start00rule*/
 
/*end00rule*/
  }
}
