package rules.EventMessage.EventFired_dir.TwilioSystem_dir

@gw.rules.RuleName("TwilioSMSSystem")
internal class TwilioSMSSystem {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
/*start00rule*/
return messageContext.Root typeis TwilioSMS
/*end00rule*/
}

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*/
 
/*end00rule*/
  }
}
